### PR TITLE
Update app bundle

### PR DESCRIPTION
**Pull request by eugenesvk**
- Doesn't require a direct link/symlink to python
- Runs in the background (as before)
- Strip "nib" file (as before)

(would still like to silence non-errors and remove the progress bar, but will do it in my own fork)

### CODE REVIEW

**Comment by dandavison** [comment]
On my Mac it takes a second or two to open a file in VSCode. As a result, I actually found that I really like having the progress bar, maybe for purely psychological reasons (it provides visual distraction while I'm waiting).

What does "run in background" mean?

**Comment by eugenesvk** [comment]
Background means it doesn't flash in the Dock, so it also adds to the role of a "silent passthru": no bars, no docks

**Comment by dandavison** [comment]
OK thanks, I keep the Dock hidden unless I'm using it so I probably wouldn't notice. I tried now (using OpenInEditor from master) and I see the VSCode dock icon do something when it's opening, but I don't see OpenInEditor/Platypus.

**Comment by eugenesvk** [comment]
yeah, it only works for when you double click the app itself, doesn't seem to help when you click the link from the terminal

**Comment by eugenesvk** [comment]
interestingly, I actually don't see any progress bar when launching links from the terminal (even when I close the editor, so it takes a second), only when opening the app directly

**Comment by eugenesvk** [comment]
actually, your app was already built with a 'run in the background' checked per your commit notes :)
so nothing changed here
I've restored the progress bar if you like it (will myself just use one without it)
So the only change then is fixing the python link and updating Platypus (icon)

**Comment by dandavison** [comment]
Thanks. Can you explain the Python link issue (this diff is pretty opaque so hard to review normally).

Re the non-error log calls, how about we introduce functions with names like `log_error` and `log_debug` and make the latter a no-op, or something like that?

**Comment by eugenesvk** [comment]
It only changes one line from `python` (which might not exist and for some reasons doesn't work for me even with proper symlinks) to `env`, that's it, then `env` hasbang in the actualy script ensures that the python script works when called without the user needing to do anything except having a python env can find

Here are the two bundle plist [diffs](https://gist.github.com/eugenesvk/6320eb67bbf541b78a759bf0ef9f42cd)

**Comment by dandavison** [comment]
OK thanks for explaining, I agree using `env` like that is better. Merged.

**Comment by eugenesvk** [comment]
just a tad too soon, I've just added the logs :)

**Pull request merged**
